strategy:
  name: Strangle
  slippage: 1.0
  symbol: nifty
  # 0	=Sunday 1=Monday 2=Tuesday 3=Wednesday 4=Thursday 5=Friday 6=Saturday
  days_to_run: 3,4
  stop:
    - type: stop_type_time
      time: 15:20
    - type: stop_type_mtm_amount
      amount: -10000
  legs:
    - lots: 6
      buy_or_sell: sell
      ce_or_pe: CE
      strike_selection:
        type: strike_selection_type_distance_from_atm
        distance_from_atm: 50
        #type: strike_selection_type_near_ltp
        #near_ltp: 15
        #type: strike_selection_type_range_ltp
        #min_ltp: 10
        #max_ltp: 25
      entry:
        - type: entry_type_time
          time: 09:18
      exit:
        - type: exit_type_time
          time: 15:25
        - type: exit_type_ltp_loss_percent
          percent: 55.0
        - type: exit_type_underlying_moved_percent
          percent: 1.0
          underlying: spot
    - lots: 6
      buy_or_sell: sell
      ce_or_pe: PE
      strike_selection:
        type: strike_selection_type_distance_from_atm
        distance_from_atm: -50
        #type: strike_selection_type_near_ltp
        #near_ltp: 15
        #type: strike_selection_type_range_ltp
        #min_ltp: 10
        #max_ltp: 25
      entry:
        - type: entry_type_time
          time: 09:18
      exit:
        - type: exit_type_time
          time: 15:25
        - type: exit_type_ltp_loss_percent
          percent: 55.0
        - type: exit_type_underlying_moved_percent
          percent: 1.0
          underlying: spot
